aws:
  enabled: true
  s3:
    region: ${AWS_S3_REGION}
    http-client:
      max-connections: 1000
      connection-timeout-seconds: 5
      socket-timeout-seconds: 5
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: stag,prod
