spring:
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
      fail-on-null-for-primitives: true
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
