spring:
  cloud:
    gcp:
      credentials:
        location: ${GOOGLE_APPLICATION_CREDENTIALS}
      sql:
        enabled: false
      project-id: ${GCP_PROJECT_ID}

  application:
    name: finder-compiler-api
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
    include:
      - actuator
      - server
      - web
      - gcp
      - solidity
      - springdoc
---
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    livereload:
      enabled: true
