spring:
  cloud:
    gcp:
      credentials:
        location: ${GOOGLE_APPLICATION_CREDENTIALS}
      sql:
        enabled: false
      project-id: ${GCP_PROJECT_ID}
  application:
    name: finder-api
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: common/messages/messages
    encoding: UTF-8
  profiles:
    active: prodBaobab
    group:
      stagBaobab: stag,stagBaobab
      stagCypress: stag,stagCypress
      prodBaobab: prod,prodBaobab
      prodCypress: prod,prodCypress
    include:
      - actuator
      - server
      - web
      - db
      - db-set1
      - db-set2
      - db-set3
      - db-set4
      - gcp
      - redis
      - client
      - springdoc
      - chain
      - kns
      - images
      - opensearch
      - zookeeper
      - settingmanager
---
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    livereload:
      enabled: true