finder:
  clients:
    http:
      max-connections: 1000
      connection-timeout-seconds: 3s
      socket-timeout-seconds: 60s
    urls:
      contract-compiler: ${COMPILER_API_ENDPOINT}
      square-api: https://square-api.klaytn.foundation
      square-web: https://square.klaytn.foundation
      coin-market-cap: https://pro-api.coinmarketcap.com/
    keys:
      coin-market-cap: "${CMC_PRO_API_KEY}"
      sendgrid-api-key: "${SENDGRID_API_KEY}"
      jwt-secret: "${JWT_SECRET}"
---
spring:
  config:
    activate:
      on-profile: stag,prod

finder:
  clients:
    urls:
      contract-compiler: ${COMPILER_API_ENDPOINT}
