spring:
  config:
    activate:
      on-profile: stagBaobab,prodBaobab

finder:
  kns:
    enabled: false

---

spring:
  config:
    activate:
      on-profile: stagCypress,prodCypress

finder:
  kns:
    enabled: true
    registry-contract-address: "0x0892ed3424851d2Bab4aC1091fA93C9851Eb5d7D"
    reverse-record-contract-address: "0x87f4483E4157a6592dd1d1546f145B5EE22c790a"
