spring:
  db:
    common-property:
      datasource:
        url-prefix: jdbc:mysql
        url-suffix: '?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull'
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        connection-timeout: 3000
      hibernate:
        ddl-auto: validate
        generate-statistics: true
---
spring:
  config:
    activate:
      on-profile: dev

  db:
    common-property:
      hibernate:
        ddl-auto: validate
        generate-statistics: true
---
spring:
  config:
    activate:
      on-profile: stag,prod

  db:
    common-property:
      hibernate:
        ddl-auto: validate
        generate-statistics: false