finder:
  images:
    contract:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: stag,prod

finder:
  images:
    contract:
      enabled: true
      gcs-bucket: ${GCS_PUBLIC_BUCKET}
      url-prefix: ${GCP_CDN_URL}
