server:
  port: 8080
  shutdown: graceful
  max-http-header-size: 16KB

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: stag,prod

